# ---- Site basics ----
title: Software Development and Cloud Computing Expertise, Advice and Certification Tips
description: A place for developers, DevOps engineers, Cloud Practitioners and AI & ML architects to share ideas and thoughts.
email: info@mcnz.com
url: "https://www.mcnz.com"
baseurl: ""                # keep "" for root at apex domain
timezone: America/Toronto
permalink: none



# Remove minima if you’re using custom layouts
# theme: minima

incremental: true
watch: true

# ---- Build & markdown ----
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
sass:
  style: compressed

# ---- Plugins (safe, non-intrusive)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-include-cache
  # - jekyll-feed           # enable if you have a blog

# ---- Include / Exclude ----
include:
  - ".well-known"          # lets you serve /.well-known/*
exclude:
  - node_modules
  - vendor
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
  - scripts
  - "**/*.map"             # optional: stops maps from being copied if present


# ---- Defaults (front-matter fallbacks) ----
defaults:
  - scope:
      path: ""             # everything
      type: exams
    values:
      layout: exam         # your custom layout: _layouts/exam.html
      toc: false
      sitemap: true

  - scope:
      path: "aws/practitioner"
    values:
      exam_type: "AWS"
      exam_name: "Cloud"
      exam_level: "Practitioner"

# ---- SEO tag config (used by jekyll-seo-tag)
logo: /assets/images/logo.png
social:
  name: Certification Exams Pro
  links:
    - https://x.com/yourhandle
    - https://github.com/yourorg

# ---- Production vs Dev overrides (optional)
# Create _config.dev.yml and run: jekyll serve --config _config.yml,_config.dev.yml
# Example _config.dev.yml:
# url: "http://localhost:4000"
# baseurl: ""
# jekyll_env: development
